version: '3'

services:
  app_cldraw:
    build: ClDrawSimulator
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://cldraw:5432/cldraw?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: postgres
      DB_PASSWORD: postgres
    restart: always
    depends_on:
      cldraw:
          condition: service_healthy
  cldraw:
    image: postgres:16.4
    ports:
      - "3307:3306"
    environment:
      POSTGRES_USER: postgres         
      POSTGRES_PASSWORD: postgres      
      POSTGRES_DB: cldraw
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      retries: 10